version: "3"

services:
  # database:
  #   image: "postgres"
  #   container_name: db-pg
  #   ports:
  #     - "5432:5432"
  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload"
    container_name: fastapi
    # external_links:
    #   - db-pg:db-pg
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - database
