version: "3"

services:
  database:
    image: "postgres:13"
    container_name: db-pg
    env_file:
      - pg.env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload"
    container_name: fastapi
    env_file:
      - pg.env
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - database
