"""added users table

Revision ID: 218bfeece674
Revises: f6898735db87
Create Date: 2022-08-13 02:08:45.606955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218bfeece674'
down_revision = 'f6898735db87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
