"""init

Revision ID: 32443b0e8807
Revises: 
Create Date: 2022-08-11 21:29:35.876592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32443b0e8807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
