"""added user relationship to store model

Revision ID: 3b953d5b175c
Revises: 998beeadd0b4
Create Date: 2022-08-14 10:10:23.679747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b953d5b175c'
down_revision = '998beeadd0b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'stores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'date_created')
    op.drop_column('stores', 'user_id')
    # ### end Alembic commands ###
