"""added users table

Revision ID: 5474642339ad
Revises: 59a27c666fec
Create Date: 2022-08-13 01:42:09.736501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5474642339ad'
down_revision = '59a27c666fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
