"""empty message

Revision ID: 701fe9d3171f
Revises: 3ceec20880ae
Create Date: 2022-08-14 20:09:41.482106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701fe9d3171f'
down_revision = '3ceec20880ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
