"""created Store, Product, StoreProduct

Revision ID: 989632946270
Revises: 3b953d5b175c
Create Date: 2022-08-14 14:51:59.871078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989632946270'
down_revision = '3b953d5b175c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'product_id', name='_store_product_uc')
    )
    op.create_index(op.f('ix_store_products_id'), 'store_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_products_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
