"""added store model

Revision ID: 998beeadd0b4
Revises: 5204d61bf36b
Create Date: 2022-08-14 08:14:26.177768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998beeadd0b4'
down_revision = '5204d61bf36b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
