"""created user model

Revision ID: eb0d14e44136
Revises: 32443b0e8807
Create Date: 2022-08-12 14:07:23.454470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0d14e44136'
down_revision = '32443b0e8807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
