"""created user table

Revision ID: ebead84b4e4e
Revises: eb0d14e44136
Create Date: 2022-08-12 23:33:21.160131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebead84b4e4e'
down_revision = 'eb0d14e44136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
