"""added AbstractProductTransaction and ProductSupply

Revision ID: f356aa13be5a
Revises: 989632946270
Create Date: 2022-08-14 15:38:24.636228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f356aa13be5a'
down_revision = '989632946270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_supplies',
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_supplies_id'), 'product_supplies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_supplies_id'), table_name='product_supplies')
    op.drop_table('product_supplies')
    # ### end Alembic commands ###
