"""added users table

Revision ID: f7fda0e49801
Revises: ebead84b4e4e
Create Date: 2022-08-13 01:39:04.353011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fda0e49801'
down_revision = 'ebead84b4e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
